// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: precious_metals.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PreciousMetalsService_FetchPrices_FullMethodName    = "/preciousmetals.PreciousMetalsService/FetchPrices"
	PreciousMetalsService_GetLatestPrice_FullMethodName = "/preciousmetals.PreciousMetalsService/GetLatestPrice"
)

// PreciousMetalsServiceClient is the client API for PreciousMetalsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PreciousMetalsServiceClient interface {
	FetchPrices(ctx context.Context, in *FetchPricesRequest, opts ...grpc.CallOption) (*FetchPricesResponse, error)
	GetLatestPrice(ctx context.Context, in *GetLatestPriceRequest, opts ...grpc.CallOption) (*GetLatestPriceResponse, error)
}

type preciousMetalsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPreciousMetalsServiceClient(cc grpc.ClientConnInterface) PreciousMetalsServiceClient {
	return &preciousMetalsServiceClient{cc}
}

func (c *preciousMetalsServiceClient) FetchPrices(ctx context.Context, in *FetchPricesRequest, opts ...grpc.CallOption) (*FetchPricesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchPricesResponse)
	err := c.cc.Invoke(ctx, PreciousMetalsService_FetchPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *preciousMetalsServiceClient) GetLatestPrice(ctx context.Context, in *GetLatestPriceRequest, opts ...grpc.CallOption) (*GetLatestPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestPriceResponse)
	err := c.cc.Invoke(ctx, PreciousMetalsService_GetLatestPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PreciousMetalsServiceServer is the server API for PreciousMetalsService service.
// All implementations must embed UnimplementedPreciousMetalsServiceServer
// for forward compatibility.
type PreciousMetalsServiceServer interface {
	FetchPrices(context.Context, *FetchPricesRequest) (*FetchPricesResponse, error)
	GetLatestPrice(context.Context, *GetLatestPriceRequest) (*GetLatestPriceResponse, error)
	mustEmbedUnimplementedPreciousMetalsServiceServer()
}

// UnimplementedPreciousMetalsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPreciousMetalsServiceServer struct{}

func (UnimplementedPreciousMetalsServiceServer) FetchPrices(context.Context, *FetchPricesRequest) (*FetchPricesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchPrices not implemented")
}
func (UnimplementedPreciousMetalsServiceServer) GetLatestPrice(context.Context, *GetLatestPriceRequest) (*GetLatestPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestPrice not implemented")
}
func (UnimplementedPreciousMetalsServiceServer) mustEmbedUnimplementedPreciousMetalsServiceServer() {}
func (UnimplementedPreciousMetalsServiceServer) testEmbeddedByValue()                               {}

// UnsafePreciousMetalsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PreciousMetalsServiceServer will
// result in compilation errors.
type UnsafePreciousMetalsServiceServer interface {
	mustEmbedUnimplementedPreciousMetalsServiceServer()
}

func RegisterPreciousMetalsServiceServer(s grpc.ServiceRegistrar, srv PreciousMetalsServiceServer) {
	// If the following call panics, it indicates UnimplementedPreciousMetalsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PreciousMetalsService_ServiceDesc, srv)
}

func _PreciousMetalsService_FetchPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreciousMetalsServiceServer).FetchPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreciousMetalsService_FetchPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreciousMetalsServiceServer).FetchPrices(ctx, req.(*FetchPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PreciousMetalsService_GetLatestPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreciousMetalsServiceServer).GetLatestPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PreciousMetalsService_GetLatestPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreciousMetalsServiceServer).GetLatestPrice(ctx, req.(*GetLatestPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PreciousMetalsService_ServiceDesc is the grpc.ServiceDesc for PreciousMetalsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PreciousMetalsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "preciousmetals.PreciousMetalsService",
	HandlerType: (*PreciousMetalsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchPrices",
			Handler:    _PreciousMetalsService_FetchPrices_Handler,
		},
		{
			MethodName: "GetLatestPrice",
			Handler:    _PreciousMetalsService_GetLatestPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "precious_metals.proto",
}
