// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: precious_metals.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metal         string                 `protobuf:"bytes,1,opt,name=metal,proto3" json:"metal,omitempty"`       // "gold", "silver", "platinum", "palladium"
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"` // "USD", "EUR", "GBP"
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`         // "grams", "ounces", "kilograms"
	Timeline      string                 `protobuf:"bytes,4,opt,name=timeline,proto3" json:"timeline,omitempty"` // "month", "year", "5year", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchPricesRequest) Reset() {
	*x = FetchPricesRequest{}
	mi := &file_precious_metals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPricesRequest) ProtoMessage() {}

func (x *FetchPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_precious_metals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPricesRequest.ProtoReflect.Descriptor instead.
func (*FetchPricesRequest) Descriptor() ([]byte, []int) {
	return file_precious_metals_proto_rawDescGZIP(), []int{0}
}

func (x *FetchPricesRequest) GetMetal() string {
	if x != nil {
		return x.Metal
	}
	return ""
}

func (x *FetchPricesRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FetchPricesRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *FetchPricesRequest) GetTimeline() string {
	if x != nil {
		return x.Timeline
	}
	return ""
}

type PriceDataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix timestamp in milliseconds
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // ISO date string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceDataPoint) Reset() {
	*x = PriceDataPoint{}
	mi := &file_precious_metals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceDataPoint) ProtoMessage() {}

func (x *PriceDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_precious_metals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceDataPoint.ProtoReflect.Descriptor instead.
func (*PriceDataPoint) Descriptor() ([]byte, []int) {
	return file_precious_metals_proto_rawDescGZIP(), []int{1}
}

func (x *PriceDataPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PriceDataPoint) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceDataPoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type PriceStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	High          float64                `protobuf:"fixed64,1,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,2,opt,name=low,proto3" json:"low,omitempty"`
	Open          float64                `protobuf:"fixed64,3,opt,name=open,proto3" json:"open,omitempty"`
	Close         float64                `protobuf:"fixed64,4,opt,name=close,proto3" json:"close,omitempty"`
	Average       float64                `protobuf:"fixed64,5,opt,name=average,proto3" json:"average,omitempty"`
	Change        float64                `protobuf:"fixed64,6,opt,name=change,proto3" json:"change,omitempty"`
	ChangePct     float64                `protobuf:"fixed64,7,opt,name=change_pct,json=changePct,proto3" json:"change_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceStatistics) Reset() {
	*x = PriceStatistics{}
	mi := &file_precious_metals_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceStatistics) ProtoMessage() {}

func (x *PriceStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_precious_metals_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceStatistics.ProtoReflect.Descriptor instead.
func (*PriceStatistics) Descriptor() ([]byte, []int) {
	return file_precious_metals_proto_rawDescGZIP(), []int{2}
}

func (x *PriceStatistics) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *PriceStatistics) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *PriceStatistics) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *PriceStatistics) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *PriceStatistics) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *PriceStatistics) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *PriceStatistics) GetChangePct() float64 {
	if x != nil {
		return x.ChangePct
	}
	return 0
}

type FetchPricesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metal          string                 `protobuf:"bytes,1,opt,name=metal,proto3" json:"metal,omitempty"`
	Currency       string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Unit           string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Timeline       string                 `protobuf:"bytes,4,opt,name=timeline,proto3" json:"timeline,omitempty"`
	CurrentPrice   float64                `protobuf:"fixed64,5,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	HistoricalData []*PriceDataPoint      `protobuf:"bytes,6,rep,name=historical_data,json=historicalData,proto3" json:"historical_data,omitempty"`
	Statistics     *PriceStatistics       `protobuf:"bytes,7,opt,name=statistics,proto3" json:"statistics,omitempty"`
	DataSource     string                 `protobuf:"bytes,8,opt,name=data_source,json=dataSource,proto3" json:"data_source,omitempty"`
	FromCache      bool                   `protobuf:"varint,9,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FetchPricesResponse) Reset() {
	*x = FetchPricesResponse{}
	mi := &file_precious_metals_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPricesResponse) ProtoMessage() {}

func (x *FetchPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_precious_metals_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPricesResponse.ProtoReflect.Descriptor instead.
func (*FetchPricesResponse) Descriptor() ([]byte, []int) {
	return file_precious_metals_proto_rawDescGZIP(), []int{3}
}

func (x *FetchPricesResponse) GetMetal() string {
	if x != nil {
		return x.Metal
	}
	return ""
}

func (x *FetchPricesResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FetchPricesResponse) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *FetchPricesResponse) GetTimeline() string {
	if x != nil {
		return x.Timeline
	}
	return ""
}

func (x *FetchPricesResponse) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *FetchPricesResponse) GetHistoricalData() []*PriceDataPoint {
	if x != nil {
		return x.HistoricalData
	}
	return nil
}

func (x *FetchPricesResponse) GetStatistics() *PriceStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

func (x *FetchPricesResponse) GetDataSource() string {
	if x != nil {
		return x.DataSource
	}
	return ""
}

func (x *FetchPricesResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

type GetLatestPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metal         string                 `protobuf:"bytes,1,opt,name=metal,proto3" json:"metal,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestPriceRequest) Reset() {
	*x = GetLatestPriceRequest{}
	mi := &file_precious_metals_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestPriceRequest) ProtoMessage() {}

func (x *GetLatestPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_precious_metals_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestPriceRequest.ProtoReflect.Descriptor instead.
func (*GetLatestPriceRequest) Descriptor() ([]byte, []int) {
	return file_precious_metals_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestPriceRequest) GetMetal() string {
	if x != nil {
		return x.Metal
	}
	return ""
}

func (x *GetLatestPriceRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetLatestPriceRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type GetLatestPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metal         string                 `protobuf:"bytes,1,opt,name=metal,proto3" json:"metal,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DataSource    string                 `protobuf:"bytes,6,opt,name=data_source,json=dataSource,proto3" json:"data_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestPriceResponse) Reset() {
	*x = GetLatestPriceResponse{}
	mi := &file_precious_metals_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestPriceResponse) ProtoMessage() {}

func (x *GetLatestPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_precious_metals_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestPriceResponse.ProtoReflect.Descriptor instead.
func (*GetLatestPriceResponse) Descriptor() ([]byte, []int) {
	return file_precious_metals_proto_rawDescGZIP(), []int{5}
}

func (x *GetLatestPriceResponse) GetMetal() string {
	if x != nil {
		return x.Metal
	}
	return ""
}

func (x *GetLatestPriceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetLatestPriceResponse) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *GetLatestPriceResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetLatestPriceResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetLatestPriceResponse) GetDataSource() string {
	if x != nil {
		return x.DataSource
	}
	return ""
}

var File_precious_metals_proto protoreflect.FileDescriptor

const file_precious_metals_proto_rawDesc = "" +
	"\n" +
	"\x15precious_metals.proto\x12\x0epreciousmetals\"v\n" +
	"\x12FetchPricesRequest\x12\x14\n" +
	"\x05metal\x18\x01 \x01(\tR\x05metal\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x1a\n" +
	"\btimeline\x18\x04 \x01(\tR\btimeline\"X\n" +
	"\x0ePriceDataPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"\xb2\x01\n" +
	"\x0fPriceStatistics\x12\x12\n" +
	"\x04high\x18\x01 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x02 \x01(\x01R\x03low\x12\x12\n" +
	"\x04open\x18\x03 \x01(\x01R\x04open\x12\x14\n" +
	"\x05close\x18\x04 \x01(\x01R\x05close\x12\x18\n" +
	"\aaverage\x18\x05 \x01(\x01R\aaverage\x12\x16\n" +
	"\x06change\x18\x06 \x01(\x01R\x06change\x12\x1d\n" +
	"\n" +
	"change_pct\x18\a \x01(\x01R\tchangePct\"\xe6\x02\n" +
	"\x13FetchPricesResponse\x12\x14\n" +
	"\x05metal\x18\x01 \x01(\tR\x05metal\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x1a\n" +
	"\btimeline\x18\x04 \x01(\tR\btimeline\x12#\n" +
	"\rcurrent_price\x18\x05 \x01(\x01R\fcurrentPrice\x12G\n" +
	"\x0fhistorical_data\x18\x06 \x03(\v2\x1e.preciousmetals.PriceDataPointR\x0ehistoricalData\x12?\n" +
	"\n" +
	"statistics\x18\a \x01(\v2\x1f.preciousmetals.PriceStatisticsR\n" +
	"statistics\x12\x1f\n" +
	"\vdata_source\x18\b \x01(\tR\n" +
	"dataSource\x12\x1d\n" +
	"\n" +
	"from_cache\x18\t \x01(\bR\tfromCache\"]\n" +
	"\x15GetLatestPriceRequest\x12\x14\n" +
	"\x05metal\x18\x01 \x01(\tR\x05metal\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\"\xb3\x01\n" +
	"\x16GetLatestPriceResponse\x12\x14\n" +
	"\x05metal\x18\x01 \x01(\tR\x05metal\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vdata_source\x18\x06 \x01(\tR\n" +
	"dataSource2\xd0\x01\n" +
	"\x15PreciousMetalsService\x12V\n" +
	"\vFetchPrices\x12\".preciousmetals.FetchPricesRequest\x1a#.preciousmetals.FetchPricesResponse\x12_\n" +
	"\x0eGetLatestPrice\x12%.preciousmetals.GetLatestPriceRequest\x1a&.preciousmetals.GetLatestPriceResponseB<Z:github.com/mayswind/ezbookkeeping/pkg/preciousmetals/protob\x06proto3"

var (
	file_precious_metals_proto_rawDescOnce sync.Once
	file_precious_metals_proto_rawDescData []byte
)

func file_precious_metals_proto_rawDescGZIP() []byte {
	file_precious_metals_proto_rawDescOnce.Do(func() {
		file_precious_metals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_precious_metals_proto_rawDesc), len(file_precious_metals_proto_rawDesc)))
	})
	return file_precious_metals_proto_rawDescData
}

var file_precious_metals_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_precious_metals_proto_goTypes = []any{
	(*FetchPricesRequest)(nil),     // 0: preciousmetals.FetchPricesRequest
	(*PriceDataPoint)(nil),         // 1: preciousmetals.PriceDataPoint
	(*PriceStatistics)(nil),        // 2: preciousmetals.PriceStatistics
	(*FetchPricesResponse)(nil),    // 3: preciousmetals.FetchPricesResponse
	(*GetLatestPriceRequest)(nil),  // 4: preciousmetals.GetLatestPriceRequest
	(*GetLatestPriceResponse)(nil), // 5: preciousmetals.GetLatestPriceResponse
}
var file_precious_metals_proto_depIdxs = []int32{
	1, // 0: preciousmetals.FetchPricesResponse.historical_data:type_name -> preciousmetals.PriceDataPoint
	2, // 1: preciousmetals.FetchPricesResponse.statistics:type_name -> preciousmetals.PriceStatistics
	0, // 2: preciousmetals.PreciousMetalsService.FetchPrices:input_type -> preciousmetals.FetchPricesRequest
	4, // 3: preciousmetals.PreciousMetalsService.GetLatestPrice:input_type -> preciousmetals.GetLatestPriceRequest
	3, // 4: preciousmetals.PreciousMetalsService.FetchPrices:output_type -> preciousmetals.FetchPricesResponse
	5, // 5: preciousmetals.PreciousMetalsService.GetLatestPrice:output_type -> preciousmetals.GetLatestPriceResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_precious_metals_proto_init() }
func file_precious_metals_proto_init() {
	if File_precious_metals_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_precious_metals_proto_rawDesc), len(file_precious_metals_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_precious_metals_proto_goTypes,
		DependencyIndexes: file_precious_metals_proto_depIdxs,
		MessageInfos:      file_precious_metals_proto_msgTypes,
	}.Build()
	File_precious_metals_proto = out.File
	file_precious_metals_proto_goTypes = nil
	file_precious_metals_proto_depIdxs = nil
}
